## 1512108 - Võ Tiến Đạt
## 1512030 - Trần Quốc Bảo

Câu hỏi: dự đoán nhiệt độ cao nhất của ngày hôm sau | thời điểm nhiệt độ cao nhất | mô tả thời tiết ngày hôm sau một cách ngắn gọn...<br>
Lợi ích: mọi hoạt động diễn ra ngoài trời đều bị ảnh hưởng bởi thời tiết, nhất là sản xuất nông nghiệp. Vậy nếu dự đoán trước được thì ta có biện pháp phòng tránh, ứng biến.

Dữ liệu thời tiết được lấy trên trang https://DarkSky.net<br>
Về cách lấy dữ liệu trang này cung cấp 1000 requests một ngày đối với mỗi tài khoản.<br>
Dữ liệu lấy với địa điểm ở thành phố Hồ Chí Minh từ năm 1998-2017.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

In [2]:
weathers_df = pd.read_csv('weatherdata.csv')

In [3]:
weathers_df.head()

,time,summary,sunriseTime,sunsetTime,moonPhase,precipType,temperatureHigh,temperatureHighTime,temperatureLow,temperatureLowTime,...,uvIndexTime,visibility,temperatureMin,temperatureMinTime,temperatureMax,temperatureMaxTime,apparentTemperatureMin,apparentTemperatureMinTime,apparentTemperatureMax,apparentTemperatureMaxTime
0,883587600,Partly cloudy throughout the day.,883609978,883651381,0.09,rain,33.03,883638000,21.02,883695600,...,883630800,NaN,22.02,883609200,33.03,883638000,22.59,883609200,34.64,883638000
1,883674000,Partly cloudy throughout the day.,883696401,883737813,0.12,rain,33.03,883724400,21.02,883778400,...,883713600,NaN,21.02,883695600,33.03,883724400,21.63,883695600,34.64,883724400
2,883760400,Partly cloudy throughout the day.,883782824,883824245,0.16,rain,33.03,883814400,23.71,883872000,...,883800000,NaN,21.02,883778400,33.03,883814400,21.63,883778400,34.91,883818000
3,883846800,Partly cloudy throughout the day.,883869245,883910677,0.20,rain,32.32,883904400,23.71,883944000,...,883886400,NaN,23.71,883872000,32.32,883904400,24.30,883857600,35.83,883890000
4,883933200,Humid and partly cloudy throughout the day.,883955666,883997109,0.23,rain,33.51,883980000,22.82,884034000,...,883972800,NaN,23.71,883944000,33.51,883980000,24.29,883944000,37.00,883980000

In [4]:
weathers_df.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7305 entries, 0 to 7304
Data columns (total 33 columns):
time                           7305 non-null int64
summary                        7305 non-null object
sunriseTime                    7305 non-null int64
sunsetTime                     7305 non-null int64
moonPhase                      7305 non-null float64
precipType                     5144 non-null object
temperatureHigh                7305 non-null float64
temperatureHighTime            7305 non-null int64
temperatureLow                 7305 non-null float64
temperatureLowTime             7305 non-null int64
apparentTemperatureHigh        7305 non-null float64
apparentTemperatureHighTime    7305 non-null int64
apparentTemperatureLow         7305 non-null float64
apparentTemperatureLowTime     7305 non-null int64
dewPoint                       7305 non-null float64
humidity                       7305 non-null float64
pressure                       7305 non-null float64
windSpeed                      7305 non-null float64
windBearing                    7305 non-null int64
windGust                       14 non-null float64
windGustTime                   14 non-null float64
cloudCover                     7305 non-null float64
uvIndex                        7305 non-null int64
uvIndexTime                    7305 non-null int64
visibility                     4162 non-null float64
temperatureMin                 7305 non-null float64
temperatureMinTime             7305 non-null int64
temperatureMax                 7305 non-null float64
temperatureMaxTime             7305 non-null int64
apparentTemperatureMin         7305 non-null float64
apparentTemperatureMinTime     7305 non-null int64
apparentTemperatureMax         7305 non-null float64
apparentTemperatureMaxTime     7305 non-null int64
dtypes: float64(17), int64(14), object(2)
memory usage: 1.8+ MB

In [5]:
weathers_df.loc[~weathers_df.precipType.isnull(),'precipType']=1.0
weathers_df.loc[weathers_df.precipType.isnull(),'precipType']=0.0
weathers_df.drop(['windGustTime', 'windGust','visibility'], axis=1,inplace=True)

In [6]:
weathers_df.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7305 entries, 0 to 7304
Data columns (total 30 columns):
time                           7305 non-null int64
summary                        7305 non-null object
sunriseTime                    7305 non-null int64
sunsetTime                     7305 non-null int64
moonPhase                      7305 non-null float64
precipType                     7305 non-null int64
temperatureHigh                7305 non-null float64
temperatureHighTime            7305 non-null int64
temperatureLow                 7305 non-null float64
temperatureLowTime             7305 non-null int64
apparentTemperatureHigh        7305 non-null float64
apparentTemperatureHighTime    7305 non-null int64
apparentTemperatureLow         7305 non-null float64
apparentTemperatureLowTime     7305 non-null int64
dewPoint                       7305 non-null float64
humidity                       7305 non-null float64
pressure                       7305 non-null float64
windSpeed                      7305 non-null float64
windBearing                    7305 non-null int64
cloudCover                     7305 non-null float64
uvIndex                        7305 non-null int64
uvIndexTime                    7305 non-null int64
temperatureMin                 7305 non-null float64
temperatureMinTime             7305 non-null int64
temperatureMax                 7305 non-null float64
temperatureMaxTime             7305 non-null int64
apparentTemperatureMin         7305 non-null float64
apparentTemperatureMinTime     7305 non-null int64
apparentTemperatureMax         7305 non-null float64
apparentTemperatureMaxTime     7305 non-null int64
dtypes: float64(14), int64(15), object(1)
memory usage: 1.7+ MB

In [7]:
def convert_localhour(df,at):
    df[at] = pd.to_datetime(df[at],unit='s').dt.tz_localize('UTC').dt.tz_convert('Asia/Ho_Chi_Minh').dt.hour
    
def convert_localday(df,at):
    df[at] = pd.to_datetime(df[at],unit='s').dt.tz_localize('UTC').dt.tz_convert('Asia/Ho_Chi_Minh')

In [8]:
convert_localhour(weathers_df,'sunriseTime')
convert_localhour(weathers_df,'sunsetTime')
convert_localhour(weathers_df,'uvIndexTime')
convert_localday(weathers_df,'time')
convert_localhour(weathers_df,'temperatureHighTime')
convert_localhour(weathers_df,'temperatureLowTime')
convert_localhour(weathers_df,'temperatureMinTime')
convert_localhour(weathers_df,'temperatureMaxTime')
convert_localhour(weathers_df,'apparentTemperatureMinTime')
convert_localhour(weathers_df,'apparentTemperatureMaxTime')

In [9]:
weathers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7305 entries, 0 to 7304
Data columns (total 30 columns):
time                           7305 non-null datetime64[ns, Asia/Ho_Chi_Minh]
summary                        7305 non-null object
sunriseTime                    7305 non-null int64
sunsetTime                     7305 non-null int64
moonPhase                      7305 non-null float64
precipType                     7305 non-null int64
temperatureHigh                7305 non-null float64
temperatureHighTime            7305 non-null int64
temperatureLow                 7305 non-null float64
temperatureLowTime             7305 non-null int64
apparentTemperatureHigh        7305 non-null float64
apparentTemperatureHighTime    7305 non-null int64
apparentTemperatureLow         7305 non-null float64
apparentTemperatureLowTime     7305 non-null int64
dewPoint                       7305 non-null float64
humidity                       7305 non-null float64
pressure                       7305 non-null float64
windSpeed                      7305 non-null float64
windBearing                    7305 non-null int64
cloudCover                     7305 non-null float64
uvIndex                        7305 non-null int64
uvIndexTime                    7305 non-null int64
temperatureMin                 7305 non-null float64
temperatureMinTime             7305 non-null int64
temperatureMax                 7305 non-null float64
temperatureMaxTime             7305 non-null int64
apparentTemperatureMin         7305 non-null float64
apparentTemperatureMinTime     7305 non-null int64
apparentTemperatureMax         7305 non-null float64
apparentTemperatureMaxTime     7305 non-null int64
dtypes: datetime64[ns, Asia/Ho_Chi_Minh](1), float64(14), int64(14), object(1)
memory usage: 1.7+ MB

In [10]:
weathers_df.head()

,time,summary,sunriseTime,sunsetTime,moonPhase,precipType,temperatureHigh,temperatureHighTime,temperatureLow,temperatureLowTime,...,uvIndex,uvIndexTime,temperatureMin,temperatureMinTime,temperatureMax,temperatureMaxTime,apparentTemperatureMin,apparentTemperatureMinTime,apparentTemperatureMax,apparentTemperatureMaxTime
0,1998-01-01 00:00:00+07:00,Partly cloudy throughout the day.,6,17,0.09,1,33.03,14,21.02,6,...,7,12,22.02,6,33.03,14,22.59,6,34.64,14
1,1998-01-02 00:00:00+07:00,Partly cloudy throughout the day.,6,17,0.12,1,33.03,14,21.02,5,...,7,11,21.02,6,33.03,14,21.63,6,34.64,14
2,1998-01-03 00:00:00+07:00,Partly cloudy throughout the day.,6,17,0.16,1,33.03,15,23.71,7,...,7,11,21.02,5,33.03,15,21.63,5,34.91,16
3,1998-01-04 00:00:00+07:00,Partly cloudy throughout the day.,6,17,0.20,1,32.32,16,23.71,3,...,7,11,23.71,7,32.32,16,24.30,3,35.83,12
4,1998-01-05 00:00:00+07:00,Humid and partly cloudy throughout the day.,6,17,0.23,1,33.51,13,22.82,4,...,7,11,23.71,3,33.51,13,24.29,3,37.00,13